//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.05.11 at 11:11:14 PM BOT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.iec.ch/61850/2006/SCL", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.iec61850.scl.xsd.classes;
