//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.05.11 at 11:11:14 PM BOT 
//


package com.iec61850.scl.xsd.classes;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tGSESettings complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tGSESettings">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.iec.ch/61850/2006/SCL}tServiceSettings">
 *       &lt;attribute name="appID" type="{http://www.iec.ch/61850/2006/SCL}tServiceSettingsEnum" default="Fix" />
 *       &lt;attribute name="dataLabel" type="{http://www.iec.ch/61850/2006/SCL}tServiceSettingsEnum" default="Fix" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tGSESettings")
public class TGSESettings
    extends TServiceSettings
{

    @XmlAttribute
    protected TServiceSettingsEnum appID;
    @XmlAttribute
    protected TServiceSettingsEnum dataLabel;

    /**
     * Gets the value of the appID property.
     * 
     * @return
     *     possible object is
     *     {@link TServiceSettingsEnum }
     *     
     */
    public TServiceSettingsEnum getAppID() {
        if (appID == null) {
            return TServiceSettingsEnum.FIX;
        } else {
            return appID;
        }
    }

    /**
     * Sets the value of the appID property.
     * 
     * @param value
     *     allowed object is
     *     {@link TServiceSettingsEnum }
     *     
     */
    public void setAppID(TServiceSettingsEnum value) {
        this.appID = value;
    }

    /**
     * Gets the value of the dataLabel property.
     * 
     * @return
     *     possible object is
     *     {@link TServiceSettingsEnum }
     *     
     */
    public TServiceSettingsEnum getDataLabel() {
        if (dataLabel == null) {
            return TServiceSettingsEnum.FIX;
        } else {
            return dataLabel;
        }
    }

    /**
     * Sets the value of the dataLabel property.
     * 
     * @param value
     *     allowed object is
     *     {@link TServiceSettingsEnum }
     *     
     */
    public void setDataLabel(TServiceSettingsEnum value) {
        this.dataLabel = value;
    }

}
