//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.05.11 at 11:11:14 PM BOT 
//


package com.iec61850.scl.xsd.classes;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tSMVSettings complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tSMVSettings">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.iec.ch/61850/2006/SCL}tServiceSettings">
 *       &lt;sequence>
 *         &lt;element name="SmpRate1" maxOccurs="unbounded">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;minInclusive value="0"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="svID" type="{http://www.iec.ch/61850/2006/SCL}tServiceSettingsEnum" default="Fix" />
 *       &lt;attribute name="optFields" type="{http://www.iec.ch/61850/2006/SCL}tServiceSettingsEnum" default="Fix" />
 *       &lt;attribute name="smpRate2" type="{http://www.iec.ch/61850/2006/SCL}tServiceSettingsEnum" default="Fix" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tSMVSettings", propOrder = {
    "smpRate1"
})
public class TSMVSettings
    extends TServiceSettings
{

    @XmlElement(name = "SmpRate1", required = true)
    protected List<BigDecimal> smpRate1;
    @XmlAttribute
    protected TServiceSettingsEnum svID;
    @XmlAttribute
    protected TServiceSettingsEnum optFields;
    @XmlAttribute
    protected TServiceSettingsEnum smpRate2;

    /**
     * Gets the value of the smpRate1 property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the smpRate1 property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSmpRate1().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BigDecimal }
     * 
     * 
     */
    public List<BigDecimal> getSmpRate1() {
        if (smpRate1 == null) {
            smpRate1 = new ArrayList<BigDecimal>();
        }
        return this.smpRate1;
    }

    /**
     * Gets the value of the svID property.
     * 
     * @return
     *     possible object is
     *     {@link TServiceSettingsEnum }
     *     
     */
    public TServiceSettingsEnum getSvID() {
        if (svID == null) {
            return TServiceSettingsEnum.FIX;
        } else {
            return svID;
        }
    }

    /**
     * Sets the value of the svID property.
     * 
     * @param value
     *     allowed object is
     *     {@link TServiceSettingsEnum }
     *     
     */
    public void setSvID(TServiceSettingsEnum value) {
        this.svID = value;
    }

    /**
     * Gets the value of the optFields property.
     * 
     * @return
     *     possible object is
     *     {@link TServiceSettingsEnum }
     *     
     */
    public TServiceSettingsEnum getOptFields() {
        if (optFields == null) {
            return TServiceSettingsEnum.FIX;
        } else {
            return optFields;
        }
    }

    /**
     * Sets the value of the optFields property.
     * 
     * @param value
     *     allowed object is
     *     {@link TServiceSettingsEnum }
     *     
     */
    public void setOptFields(TServiceSettingsEnum value) {
        this.optFields = value;
    }

    /**
     * Gets the value of the smpRate2 property.
     * 
     * @return
     *     possible object is
     *     {@link TServiceSettingsEnum }
     *     
     */
    public TServiceSettingsEnum getSmpRate2() {
        if (smpRate2 == null) {
            return TServiceSettingsEnum.FIX;
        } else {
            return smpRate2;
        }
    }

    /**
     * Sets the value of the smpRate2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link TServiceSettingsEnum }
     *     
     */
    public void setSmpRate2(TServiceSettingsEnum value) {
        this.smpRate2 = value;
    }

}
